[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--force"  # Override dependency constraints
  CI = "false"  # This will prevent treating warnings as errors

